[package]
name = "rock-paper-scissors"
version = "0.1.0"
authors = ["Paweł Romanowski <pawroman@gmail.com>"]

[dependencies]
lazy_static = "1.4.0"
rand = "0.7.3"
strum = "0.18.0"
strum_macros = "0.18.0"